// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWevu8v2fg0bG55Rf2uThacrhNY4ULJyk',
    appId: '1:855301619316:web:f158cf7830e070cf71db21',
    messagingSenderId: '855301619316',
    projectId: 'nav-c59cd',
    authDomain: 'nav-c59cd.firebaseapp.com',
    storageBucket: 'nav-c59cd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfuTh38f6NNgROuWo6UPOxcLVXRL1_gk0',
    appId: '1:626863155820:ios:db29c3e529c615f2edc649',
    messagingSenderId: '626863155820',
    projectId: 'nav-5e00d',
    storageBucket: 'nav-5e00d.firebasestorage.app',
    iosBundleId: 'com.example.nav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfuTh38f6NNgROuWo6UPOxcLVXRL1_gk0',
    appId: '1:626863155820:ios:db29c3e529c615f2edc649',
    messagingSenderId: '626863155820',
    projectId: 'nav-5e00d',
    storageBucket: 'nav-5e00d.firebasestorage.app',
    iosBundleId: 'com.example.nav',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb0PouS_ZrKAIq1jE0YaFHXE9whZqeWJU',
    appId: '1:626863155820:web:36aafc26ee8ead21edc649',
    messagingSenderId: '626863155820',
    projectId: 'nav-5e00d',
    authDomain: 'nav-5e00d.firebaseapp.com',
    storageBucket: 'nav-5e00d.firebasestorage.app',
    measurementId: 'G-0TDMC6Q2X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGkHB35qyyCxkAvtJd4bjyZX1v-QShrSw',
    appId: '1:855301619316:android:961cfad9731a337271db21',
    messagingSenderId: '855301619316',
    projectId: 'nav-c59cd',
    storageBucket: 'nav-c59cd.firebasestorage.app',
  );
}
